# image: https://hub.docker.com/r/bitnami/suitecrm
# docs: https://github.com/bitnami/bitnami-docker-suitecrm

version: '3.8'

services:
  oracledb:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-mysql
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: always

networks:
  default:
      name: ${APP_NAME}

volumes:
  oracledb:
