# image: https://container-registry.oracle.com/ords/f?p=113:10::::::
# docs: http://docs.oracle.com/en/database/

version: '3.8'

services:
  oracledb:
    image: container-registry.oracle.com/database/${DB_ORACLE_EDITION}:${DB_ORACLE_VERSION}
    container_name: ${APP_NAME}-oracledb  
    environment:
      ORACLE_CHARACTERSET: ${DB_CHARACTERSET}
      ORACLE_PWD: ${DB_ORACLE_PASSWORD}
      ORACLE_SID: ${DB_ORACLE_SID}
      ORACLE_PDB: ${DB_ORACLE_PDB}
      INIT_SGA_SIZE: ${DB_ORACLE_SGA}
      INIT_PGA_SIZE: ${DB_ORACLE_PGA}
      ENABLE_ARCHIVELOG: true
    volumes:
      - oracledb:/opt/oracle/oradata
    ports:
      -  ${DB_ORACLE_PORT}:1521
      -  ${DB_MANAGE_PORT}:5500
    restart: always

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  oracledb:
