# image: https://container-registry.oracle.com/ords/f?p=113:10::::::

version: '3.8'

services:
  oracledb:
    image: container-registry.oracle.com/database/express:${DB_ORACLE_VERSION}
    container_name: ${APP_CONTAINER_NAME}  
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: always

networks:
  default:
      name: ${APP_NAME}

volumes:
  oracledb:
